source 'https://coding.net/u/hging/p/Specs/git'

platform :ios, '8.0'
use_frameworks!

target 'GankIO' do

pod 'AFNetworking', '~> 3.1.0'
pod 'ReactiveCocoa', '~> 4.2.1'
pod 'Mantle', '~> 2.0.7'

end

