#source 'https://coding.net/u/hging/p/Specs/git'

platform :ios, '8.0'
use_frameworks!

target 'GankIO' do

pod 'AFNetworking'
pod 'ReactiveCocoa', '~> 2.5'
pod 'Mantle', '~> 2.0.7'
pod 'KINWebBrowser'

end

